# example
stages:
  - name: Build
    # Conditions for stages
    when:
      branch: master
      event: [ push, pull_request ]
    # Multiple steps run concurrently
  - name: Publish my image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: custom163/gc:v0.0.1
        # Optionally push to remote registry
        pushRemote: false
