apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    workload.user.cattle.io/workloadselector: deployment-default-www
  name: www
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: www
        version: v1
    spec:
      containers:
      - image: docker-registry/custom163/gc
        imagePullPolicy: Always
        name: www
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
##########################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  generation: 1
  labels:
    app: www
  name: www
  namespace: default
  spec:
  rules:
  - host: www.247nub.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 80
 
