apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: default
spec:
  selector:
    matchLables:
      app: www
  replicas: 1
  template:
    metadata:
      labels:
        app: www
        version: v1
    spec:
      containers:
      - image: docker-registry/custom163/gc:0.0.1
        name: www
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        
##########################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  generation: 1
  labels:
    app: www
  name: www
  namespace: default
  spec:
  rules:
  - host: www.247nub.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 80
 
