kind: Service
apiVersion: v1
metadata:
  name: www
spec:
  selector:
    app: www
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: www
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080 
---
##########################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www
  namespace: default
spec:
  rules:
  - host: www.247nub.com
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 80
 
